apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-pod
  labels:
    app: myapp
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "init-myservice",
            "image": "busybox",
            "command": ["sh", "-c", "mkdir /var/log/$(POD_NAME)"],
            "volumeMounts": [{ "name": "init-path", "mountPath": "/var/log"}] 
        }
    ]'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
      - name: myapp-container
        image: busybox
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        volumeMounts: 
        - mountPath: /var/log/
          name: container-log
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      volumes:
      - name: init-path
        hostPath:
          path: /var/log
      - name: container-log
        hostPath: 
        path: /var/log/myapp-pod/

