apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_lABEL
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-test
      volumes:
      - name: nginx-test
        hostPath:
          path: /data/container-nginx
      hostNetwork: true

