apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "init-myservice",
                "image": "busybox",
                "imagePullPolicy": "IfNotPresent",
                "command": ["sh", "-c", "touch /var/message\n
                                         touch /var/secure\n
                                         touch /var/btmp
                             "],
                "volumeMounts": [{ "name": "nginx-test", "mountPath": "/var"}]
            }
        ]'
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "
                echo $PODIP > /data/$PODIP\n
                [ -f /var/log/message ] && rm /var/log/message;ln -s /data/message /var/log/message;\n
                [ -f /var/log/secure ] && rm /var/log/secure;ln -s /data/secure /var/log/secure;\n
                [ -f /var/log/btmp ] && rm /var/log/btmp;ln -s /data/btmp /var/log/btmp;
                "]
        env:
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
        - mountPath: /data
          name: nginx-test
      volumes:
      - name: nginx-test
        hostPath:
          path: /data/nginx/nginx-container/
      hostNetwork: true

