apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['10.211.55.4:9090']
    - job_name: 'kube-apiserver'
      scheme: http
      static_configs:
        - targets: ['10.211.55.4:8080','10.50.32.111:8080']
    - job_name: 'kubernetes-nodes-cadvisor'
      kubernetes_sd_configs:
      - api_servers: 
        - 'http://10.50.32.111:8080'
        role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - source_labels: [__meta_kubernetes_role]
        action: replace
        target_label: kubernetes_role
        #将默认10250端口改成10255端口
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:10255'
        target_label: __address__
    #以下是监控每个宿主机，需要安装node-exporter    
    - job_name: 'kubernetes_node'
      kubernetes_sd_configs:
      - api_servers:
        - 'http://10.211.55.4:8080'
        role: node
      relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:31672'
        target_label: __address__


       
