apiVersion: v1
kind: Service
metadata:
  annotations: 
    prometheus.io/scrape: 'true'
  name: kube-state-metrics
  namespace: monitoring
  labels:
    app: kube-state-metrics
spec:
  ports:
  - name: kube-state-metrics    
    port: 8080
    nodePort: 32223
    protocol: TCP
  type: NodePort
  selector:
    app: kube-state-metrics

