apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: prometheus-node-exporter
    namespace: monitoring
    labels:
      app: prometheus
      component: node-exporter
spec:
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        app: prometheus
        component: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        name: prometheus-node-exporter
        ports:
        - containerPort: 9100
          protocol: TCP


