apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: node-exporter
spec:
  ports:
  - name: prometheus-node-exporter       
    port: 9100
    nodePort: 32222
    protocol: TCP
  type: NodePort
  selector:
    app: prometheus
    component: node-exporter

